### ISSUE TITLE
Context URL and the links it contains are invalid

### ISSUE THREAD

**Issue by WesIngwersen** [GreenDelta/olca-schema#6]
openLCA JSON_LD typically contains
`@context":"http://greendelta.github.io/olca-schema/context.jsonld`
which breaks

It  refers to what appears to be this file
https://github.com/GreenDelta/olca-schema/blob/03a7953606db4b1d383169649a49bcd80d9480e7/context.jsonld#L1
which itself contains URLs for the schema that break

**Comment by bkuczenski** [comment]
It just needs to be added to the "docs" folder so that it appears as a static resource

**Comment by msrocka** [comment]
copied it to the docs folder so that the URL http://greendelta.github.io/olca-schema/context.jsonld should work now.

> which itself contains URLs for the schema that break

note that these are not URLs but namespace URIs

**Comment by bkuczenski** [comment]
thanks

**Comment by WesIngwersen** [comment]
I remember when URIs came out with XML, but to this day I do not see the value in including namespace URIs that don't resolve as valid URLs. In this case, while the context.jsonld file might be valid under the JSON-LD spec, I don't see any value with it otherwise, either for machines or humans.

**Comment by msrocka** [comment]
These URIs (or IRIs) are an essential part of the linked data specification and the semantic stack: they serve as identifiers of things (and do not have to resolve to something). With these URIs, the property `unit` in a JSON document would expand to `http://openlca.org/schema/v1.0/unit`. And in another document with another context `unit` could mean something different than in the openLCA schema (and would expand to another URI). True, that it is nice when such an URI resolves to the documentation of that thing that it describes, but the main purpose here is to get identifiers without clashes... That said, as data sets in the openLCA schema are not used as linked data, I agree that this is overhead without much value.
