### ISSUE TITLE
AttributeError on `datetime.UTC` which requires Python >= 3.11

### ISSUE THREAD

**Issue by bl-young** [GreenDelta/olca-schema#9]
`datetime.UTC` I believe requires python 3.11 and so generates an AttributeError for 3.9 and 3.10.

olca-schema indicates it should work for[ python >=3.9](https://github.com/GreenDelta/olca-schema/blob/master/py/pyproject.toml#L10)

Implemented in this commit (I think): d5ccd6012b286c6231e23d565aca9567263664a8

I think that `datetime.timezone.utc` might work instead of `datetime.UTC`

**Comment by bl-young** [comment]
We try to maintain our packages at least back to python 3.9, and this update is breaking that.

**Comment by msrocka** [comment]
Thanks Ben, I changed it to `datetime.timezone.utc` in the 2.2.2 version, does that work?

**Comment by bl-young** [comment]
yes thank you!
